In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import glob
import re
import math

In [2]:
votes_df=pd.read_csv('../data/voter_numbers_2024.csv')

In [3]:
seat_share_2024=pd.read_csv('../data/seat_share_2024.csv')
compactness = pd.read_csv('../data/compactness_scores_simulations.csv')
rep_numbers=pd.read_csv('../data/rep_numbers.csv')
len(rep_numbers.loc[rep_numbers['Districts']<8])

28

In [4]:
enacted_map=pd.read_csv('../enacted_map.csv')
alternate_map=pd.read_csv('../alt_map.csv')

In [5]:
enacted_reock_min = enacted_map['Reock'].min()
alternate_reock_min = alternate_map['Reock'].min()

In [6]:
#create dataframe of simulated maps with seat share and Reock min score of map
dem1=pd.DataFrame(columns=['dem_seats', 'rep_seats', 'Reock_min'])

In [7]:
dem1.loc[:,'dem_seats']=seat_share_2024['dem_seats']
dem1.loc[:, 'rep_seats']=seat_share_2024['rep_seats']
dem1.loc[:,'Reock_min']=compactness['Reock_min']
dem1

     dem_seats rep_seats Reock_min
0            0         4  0.332951
1            0         4  0.448682
2            0         4  0.361399
3            1         3  0.428981
4            0         4  0.334623
..         ...       ...       ...
255          1         3  0.377538
256          0         4  0.401156
257          0         4  0.347251
258          0         4  0.448234
259          0         4    0.4304

[260 rows x 3 columns]

In [8]:
dem1.loc[dem1['rep_seats']==2]

     dem_seats rep_seats Reock_min
205          2         2  0.193502

In [ ]:
# search for simulated maps with at 1 democratic seat and a Reock min at least as good as the enacted map's Reock min score
dem1.loc[(dem1['rep_seats']==3) & (dem1['Reock_min']>=enacted_reock_min)]

     dem_seats rep_seats Reock_min
3            1         3  0.428981
51           1         3  0.357298
59           1         3  0.411182
82           1         3   0.38317
87           1         3  0.387269
89           1         3  0.378544
91           1         3    0.3973
98           1         3  0.378136
108          1         3  0.429219
113          1         3  0.424463
114          1         3  0.393984
136          1         3  0.376417
137          1         3  0.389957
138          1         3   0.36156
139          1         3  0.396382
169          1         3  0.386328
174          1         3  0.403398
181          1         3  0.358001
182          1         3  0.384293
185          1         3  0.391314
194          1         3  0.374623
195          1         3  0.399729
202          1         3  0.378544
208          1         3  0.408196
214          1         3  0.381354
252          1         3  0.366097
255          1         3  0.377538